defi_revenue_attribution:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', 'localhost') }}"
      port: "{{ env_var('DB_PORT', '5433') | int }}"
      user: "{{ env_var('DB_USER', 'pipeline') }}"
      password: "{{ env_var('DB_PASSWORD', 'pipeline_secret') }}"
      dbname: "{{ env_var('DB_NAME', 'defi_pipeline') }}"
      schema: staging
      threads: 4

    prod:
      type: postgres
      host: "{{ env_var('DB_HOST') }}"
      port: "{{ env_var('DB_PORT') | int }}"
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASSWORD') }}"
      dbname: "{{ env_var('DB_NAME') }}"
      schema: staging
      threads: 4

    ci:
      type: postgres
      host: localhost
      host: 127.0.0.1
      user: pipeline
      pass: pipeline_secret
      port: 5433
      dbname: defi_pipeline
      schema: staging_ci
      threads: 2
